apiVersion: config.k8s.torproject.org/v2
kind: ProjectConfig
meta:
  name: tor-controller-config
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 59806307.k8s.torproject.org
torDaemon:
  image: ghcr.io/rinsecode/tor-daemon:latest
torDaemonManager:
  image: ghcr.io/rinsecode/tor-daemon-manager:latest
torOnionbalanceManager:
  image: ghcr.io/rinsecode/tor-onionbalance-manager:latest
